### ISSUE TITLE
AttributeError: 'Converter' object has no attribute 'theme'

### ISSUE THREAD

**Issue by aruone** [xtonousou/mobaxterm_to_remmina#1]
Hello!
When I tried to run the script without any additional argument I got this error:
```
Traceback (most recent call last):
  File "/home/aru/./mobaxterm2remmina.py", line 503, in <module>
    Converter().to_remmina()
  File "/home/aru/./mobaxterm2remmina.py", line 485, in to_remmina
    theme=self.theme)
AttributeError: 'Converter' object has no attribute 'theme'
```
I kinda fixed it myself by adding `self.theme = self.theme_def`  under `self.theme_def = 'Linux'` inside init self function of Converter class. It worked flawlessly after.
Thank you for putting your time into this script, it will definitely save a lot of time for a lot of people.

**Comment by aruone** [comment]
Also got another error with `--with-passwords` argument:
```
Enter MobaXterm master password: 
Traceback (most recent call last):
  File "/home/aru/./mobaxterm2remmina.py", line 503, in <module>
    Converter().to_remmina()
  File "/home/aru/./mobaxterm2remmina.py", line 386, in __init__
    self.mobaxterm_safe = MobaXtermCryptoSafe(mobaxterm_master_password.encode('ansi'))
LookupError: unknown encoding: ansi
```
Changing `ansi` to `cp1252` fixes it.

**Comment by xtonousou** [comment]
Hey @aruone thanks for opening the issue! It would be awesome to merge your changes to upstream if you submit a PR.

**Comment by xtonousou** [comment]
Closing due to PR #2 . Thanks for contributing to the project @aruone !
